### ISSUE TITLE
error: ‘byte’ is not a member of ‘CryptoPP’

### ISSUE THREAD

**Issue by ZW-BOY1126** [laugh12321/model_crypto#1]
在编译的时候遇到了这个问题，我是有这个库的。

**Comment by ZW-BOY1126** [comment]
error: ‘byte’ is not a member of ‘CryptoPP’

**Comment by laugh12321** [comment]
报错是指向的是哪个文件的第几行呢？是用xmake编译的吗？是最新的版本吗？如果不是请下拉一下

**Comment by ZW-BOY1126** [comment]
crypto.cpp文件中的43行，CryptoPP::byte这块报错，是不是和CryptoPP的版本有关系吗？我现在用的最新的版本

**Comment by ZW-BOY1126** [comment]
用cmake编译的。

**Comment by laugh12321** [comment]
我用`xmake`编译所下载的`CryptoPP`版本为`8.7.0`, `pybind11`版本为`2.10.0`.
我不太会用`cmake`编译,所以帮不上什么忙😢，你可以参考`xmake.lua`编写`cmake`所需的`CMakeLists.txt`.

在`model_crypto`项目中，`core`为模型加密相关的核心代码，`utils`目前仅用于获取MAC地址，`core`与`utils`均以动态库的形式编译，`main.cpp`是引用`core`与`utils`编写的即用脚本。
